config {
  type: 'view'
}

select
  channel_id,
  channel_title,
  channel_views,
  country,
  relevance,
  subs,
  daily_views,
  relevant_daily_views,
  views,
  daily_impressions,
  received_daily_impressions,
  received_daily_impressions_per_view,
  avg_minutes,
  from_date,
  to_date,
  lr,
  tags,
  ideology,
  media,
  manoel,
  ain,
  logo_url
from
  ${ref('channel_stats')}
where
  meets_subsviews_criteria = true
