config {
  type: "table",
  tags: ["init"]
}

select to_date(regexp_substr(metadata$filename, 'soft_tags_([0-9]+)', 1, 1, 'e'), 'YYYYMMDD')::date as updated
     , $1::string as channel_id
     , $2::double as relevance
     , $3::string as tag
     , $4::double as confidence
     , dense_rank() over (order by updated desc) update_no
-- path directly to the latest file
from @public.yt_data/import/sam_reviews/ (file_format => tsv)