config {
  type: "table",
  dependencies: ['link_detail'],
  description: `links to YouTube videos from covid related posts (e.g. reddit or parler at the time of writing)`
}

with links as (
  select link_type
       , link_id
       , video_id_to
       , channel_id_to
       , platform_from
       , post_id_from
       , arrayuniq(regexmatchall(p.body,
                                 '(covid|coronavirus|SARS-CoV-2|vaccine|Wuhan flu|China virus|vaccinated|Pfizer|Moderna|BioNTech|AstraZeneca|Johnson \& Johnson|CDC|world health organization|Herd immunity)',
                                 'i')) words
       , r.subreddit
  from link_detail d
         join post p on p.post_id=d.post_id_from
         left join reddit_post r on r.full_link=d.post_id_from and platform_from='Reddit'
  where d.link_type in ('channel','video')
    and platform_to='YouTube'
    and (
      r.subreddit is null
      or r.subreddit not in ('u_DrillPlaylistBot','kpop','popheads','jpop','PowerMetal','Music','kpopthoughts','hiphopheads')
    )
  and array_size(words) > 0
)
  , g as (
  select iff(link_type = 'video', link_id, null) video_id
       , iff(link_type = 'channel', link_id, null) channel_id
       , array_agg(object_construct('platform',platform_from,'post_id',post_id_from,'subreddit',subreddit, 'words', words)) froms
  from links
  group by 1, 2
  order by array_size(froms) desc
)
select * from g