config {
  type: "view",
  description: `Mentions of personal vaccine hesitancy detected by sam's 0-shot learning nlp`
}

with mentions as (
  select $1:meta m, $1 v, metadata$filename file
  from @public.yt_data/import/narratives/covid_vaccine_personal_mentions
)
select m:CAPTION_GROUP::int caption_group
     , m:"CHANNEL_ID"::string channel_id
     , m:"VIDEO_ID"::string video_id
     , m:"OFFSET_SECONDS"::int offset_seconds
     , v:"text"::string caption
    , file
from mentions